project:
  type: website

lang: es

website:
  title: "Lambda"
  page-footer: "Copyright 2023, Lambda"
  navbar:
    background: primary
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/lambda657/
          
format:
  html:
    theme: flatly
    css: styles.css
    